spring:
  profiles:
    active: local

---

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: batch
    password: 1234
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false